### ISSUE TITLE
Turn this into a project on packagist

### ISSUE THREAD

**Issue by b-sharpe** [docksal/boilerplate-drupal9-blt#11]
Given this was clearly taken from `acquia/drupal-minimal-project` (another issue should be opened to update the name in composer.json), it'd be great to have this available on Packagist, that way people can just run:

`composer create-project docksal/boilerplate-drupal9-blt:<version> <project name>`

I'd suggest changing this repo to have semver tagging to allow updates as well.

**Comment by lmakarov** [comment]
This indeed is `acquia/drupal-minimal-project` with a Docksal config mixed in.

@b-sharpe aside from being able to start a project with `composer create-project docksal/boilerplate-drupal9-blt:<version> <project name>`, do you see any other reasons why this boilerplate repo should be turned into a dedicated project on Packagist?

**Comment by b-sharpe** [comment]
@lmakarov The problem is really more about the `fin project create` command than this repo itself. Allowing it to be a packagist project doesn't prevent `fin project create` from existing, but rather solves the following problems for people who spin up a lot of different Docksal/BLT projects:

1. Since this is using BLT, it's expected to be able to edit `blt/blt.yml` _BEFORE_ installing Drupal, otherwise if you want certain changes (i.e. using the standard profile instead of minimal) you then have to drop the DB and re-install afterwards.
2. Same thing with `docksal.env` / `docksal.yml`, we typically edit these before installing Drupal, especially in the case of mysql vs mariadb or php versions
3. The command sets the remote git repo to the boilerplate, if this were a packagist project, then users can init their own repo.

An alternative to making it a packagist project would be to add some more options to the init to allow optionally not running BLT setup; however, this doesn't solve bullet point 3 as well as I'm unsure if `fin project create` can pass options down to the boilerplate's init?

**Comment by lmakarov** [comment]
@b-sharpe it sounds like you want a shortcut/command that would only do the following:

```bash
git clone https://github.com/docksal/boilerplate-drupal9-blt.git my-blt-project
cd my-blt-project
rm -rf .git
composer install # Possibly, to match exactly what `composer create-project` would do
```

Then you would do the necessary adjustments to config files (BLT and Docksal) and run `fin init` as the last step. Did I get it right?

**Comment by shelane** [comment]
Also, to run a composer project command through packagist would require the user to have composer installed already on their system - possibly even with php requirements. `fin project create` runs all of the start up through a Docksal container so that the user would not need this. If you routinely create projects from a boilerplate blt and want specific blt settings, you can use a custom repo with `fin project create`.

**Comment by lmakarov** [comment]
> you can use a custom repo with `fin project create`

Great point!

@b-sharpe check this out:

```
fin project create --name=myproject --repo=https://github.com/org/project.git
```

This clones the repo into a new project folder and runs `fin init` inside it.

**Comment by b-sharpe** [comment]
I'm not sure how that helps? Passing the `--repo` bypasses using this boilerplate all together. 

We _**want**_ to use this boilerplate as it is a great way to kickstart a d9 + blt + docksal project, but we have the 3 issues above of init running **_before_** blt/docksal edits can be made and then repo has to be changed to our own (the repo being the least of the 3 to be honest).

I agree with @shelane that having a project would require the user to have composer locally which could pose issues, so possibly the solution here is additional options to the `init` command that allow NOT running blt setup so the user can make blt/docksal stack edits first. If this sounds logical then I can create a new issue/PR for that.

The repo I think would have to be a different issue tied to the main docksal project create command (i.e. passing `--local-repo` or something) which I think can be left to a later date.

**Comment by halisonfernandes** [comment]
Another thing is to auto-populate the `blt.yml` with the virtual host and machine name provided during the `project create`.

Currently we have this `blt.yml` after installation:
```
project:
  machine_name: www
  profile:
    name: minimal
```

Ideally it would be after setup:
```
project:
  machine_name: <provided by --name option>
  profile:
    name: minimal
  local:
    protocol: http
    hostname: '${project.machine_name}.docksal'
```

**Comment by b-sharpe** [comment]
See the above PR, I think this is a nice elegant solution that solves all above problems. Just a simple Y/N to allow stopping blt setup to allow a user to configure blt.yml, stack, settings, etc

**Comment by halisonfernandes** [comment]
I liked the approach of having a simple Y/N question for BLT setup.
I'd only suggest including a message like "After configuring your blt.yml run `fin blt setup` to complete your setup." before the exit.

Since it's not related to add the `asset-packagist` repository, I decided to create another ticket for this. See #16

**Comment by lmakarov** [comment]
Here's my take on this: https://github.com/docksal/boilerplate-drupal9-blt/pull/19.

@b-sharpe, @halisonfernandes any objections?

**Comment by b-sharpe** [comment]
Yes, looks like a reasonable solution, I made a comment on the PR with a couple typo fixes, but otherwise looks good.

**Comment by halisonfernandes** [comment]
Sounds good to me! Let's move forward with this @lmakarov 
Thanks!

**Comment by b-sharpe** [comment]
@lmakarov any update? I can create another PR with the typo fixes if you like, but seems redundant to fix 2 characters
