### ISSUE TITLE
Update composer.json

### ISSUE THREAD

**Issue by b-sharpe** [docksal/boilerplate-drupal9-blt#12]
composer.json should have it's meta-data updated to reflect this project, not `acquia/drupal-minimal-project`

**Comment by lmakarov** [comment]
This would only be necessary if we decide to proceed with https://github.com/docksal/boilerplate-drupal9-blt/issues/11. 
Otherwise, it's still `acquia/drupal-minimal-project` with a Docksal config mixed in.
